### ISSUE TITLE
is it true that cheerios is overwriting the previous versions itself on the official OPAM repository?

### ISSUE THREAD

**Issue by brando90** [uwplse/cheerios#19]
related: https://discuss.ocaml.org/t/is-it-true-that-the-official-opam-repository-allows-non-additive-updates-to-the-projects-packages-pushed-to-it/11432

**Comment by palmskog** [comment]
What gets installed through the opam package is determined by coq_makefile that is bundled with Coq. What gets removed when the package is removed is determined by opam. So this issue doesn't have anything to do with cheerios.
